"""empty message

Revision ID: ce4a9c7e7c2f
Revises: b73fa06cf210
Create Date: 2024-10-02 16:55:33.411622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4a9c7e7c2f'
down_revision = 'b73fa06cf210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AltArts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('releaseSet_id', sa.Integer(), nullable=True),
    sa.Column('card_image', sa.String(), nullable=True),
    sa.Column('ygopro_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Cards.id'], name=op.f('fk_AltArts_card_id_Cards')),
    sa.ForeignKeyConstraint(['releaseSet_id'], ['ReleaseSets.id'], name=op.f('fk_AltArts_releaseSet_id_ReleaseSets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_AltArts'))
    )
    # with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_CardsinDecks_deck_id', type_='unique')

    # with op.batch_alter_table('Inventories', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_Inventories_isFirstEd', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('Inventories', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_Inventories_isFirstEd', ['isFirstEd', 'user_id', 'cardinSet_id'])

    # with op.batch_alter_table('CardsinDecks', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_CardsinDecks_deck_id', ['deck_id', 'card_id', 'location'])

    op.drop_table('AltArts')
    # ### end Alembic commands ###
